//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Lab_clans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clan()
        {
            this.Clan_member = new HashSet<Clan_member>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string Clan_name { get; set; }
        public string Clan_tag { get; set; }
        public string Clan_leader { get; set; }
        public string Clan_message { get; set; }
        public Nullable<int> Clan_total_members { get; set; }
        public string Clan_message_inside { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clan_member> Clan_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}
