//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Lab_clans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan_member
    {
        public int id { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Clan_ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Clan_roles Clan_roles { get; set; }
        public virtual User User { get; set; }
        public virtual Clan Clan { get; set; }
    }
}
